### PR TITLE
automate set_locale

### PR DESCRIPTION
**Pull request by masarakki**
make more easier to use

### CODE REVIEW

**Comment by mjperrone** [comment]
bump

**Comment by DouweM** [comment]
Merged and released as 2.0.3!

**Comment by Kriechi** [comment]
I'm not sure what went wrong but it does not work for me. I get the following error:
```
[...]/gems/activesupport-4.1.8/lib/active_support/i18n_railtie.rb:49:in `block in initialize_i18n': undefined method `automatically_set_locale=' for I18n:Module (NoMethodError)
```

Rails 4.1.8 on OSX 10.9, ruby 2.1.5 with rbenv from homebrew.
```
# config/application.rb
config.i18n.enforce_available_locales = true
config.i18n.available_locales = [:en, :de]
config.i18n.automatically_set_locale = true
```

I deleted the old code from ApplicationController.

**Comment by DouweM** [comment]
Yeah, I may have jumped the gun on that one. Will look into it.

**Comment by DouweM** [comment]
Yanked v2.0.3 and released v2.0.4 which should fix this. The way to enable the feature has changed slightly: you should now set `HttpAcceptLanguage.automatically_set_locale = true` in an initializer.

**Comment by Kriechi** [comment]
At least the error is gone...
But it still seems to be broken. It does not select the correct language for me...

**Comment by DouweM** [comment]
Could you show the `Accept-Language` header you're testing this with? I've tested it in a clean Rails 4 application and it works here.

**Comment by Kriechi** [comment]
I guess the railtie is loaded before the initializer kicks in.
So the config never gets loaded...

**Comment by Kriechi** [comment]
```
request.headers['Accept-Language']
=> "de,en-US;q=0.8,en;q=0.6"
```

yet my application still shows english text (which is the default locale).

**Comment by DouweM** [comment]
Hmm, that's annoying. Could you verify if it's a race condition between the railtie and initializers by adding some logging to them? You can get to the http_accept_language source using `bundle show http_accept_language` from your project folder.

**Comment by Kriechi** [comment]
No it is no race condition. The railtie simply gets loaded before the custom initializer.
I checked by with `puts` after https://github.com/iain/http_accept_language/blob/master/lib/http_accept_language/railtie.rb#L4
and in the initializer file `config/initializers/http_accept_language.rb`.

And the output from the railtie came first. Which means it won't read the setting properly, because at this time it is still not set to true.

**Comment by DouweM** [comment]
Yeah, that's what I was referring to even if the choice of words wasn't correct. :) Thanks for verifying. Weird that it _is_ working right for me. I'll look into it.

**Comment by Kriechi** [comment]
Ok then. I even tried renaming my initializer to `config/00_aa_http_accept_language.rb` - without any luck. Seems as railties are always loaded first...

**Comment by DouweM** [comment]
Railties may always be loaded first, but the point is that in your case the `ActiveSupport.on_load :action_controller` block is called before the other initializers, which is definitely not right, since that's only supposed to run when `ActionController::Base` is loaded, which should only happen when your `ApplicationController` is loaded upon the first incoming request.

I have no idea why in your case `ActionController::Base` is being loaded before the `http_accept_language` initializer, because it definitely isn't in my case (both for a clean Rails 4.2.0 app and a large, real-life Rails 4.1.7 one.)

**Comment by Kriechi** [comment]
@DouweM @masarakki how about #45 ?

**Comment by DouweM** [comment]
Much better!

**Pull request merged**
